package com.example.myapplication.core

const val COCKTAILS_FRAGMENT_TAG = "COCKTAILS_FRAGMENT_TAG"
const val ADD_COCKTAILS_FRAGMENT_TAG = "ADD_COCKTAILS_FRAGMENT_TAG"
const val ADD_DIALOG_FRAGMENT_TAG = "ADD_DIALOG_FRAGMENT_TAG"
const val DETAIL_FRAGMENT_TAG = "DETAIL_FRAGMENT_TAG"